apiVersion: devopstoolkitseries.com/v1alpha1
kind: CompositeKubernetesCluster
metadata:
  name: team-c
  labels:
    cluster-owner: shuknk8s
spec:
  compositionRef:
    # Possible values cluster-google, cluster-azure, cluster-aws
    name: cluster-azure
  parameters:
    # Possible values small, medium, large
    nodeSize: small
    # version: "1.20"
    # minNodeCount: 2
  writeConnectionSecretToRef:
    namespace: team-c
    name: cluster-aks
